events { worker_connections 1024; }
http {
  upstream auth { server auth-service:8081; }
  upstream ws   { server realtime-service:8084; }
  server {
    listen 80;
    location /api/auth/ {
      proxy_pass http://auth/api/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location /ws/ {
      proxy_pass http://ws/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_read_timeout 86400s;
    }
  }
}
